export type EIconType = 'icon-rd-party-software' |
'icon-accessories' |
'icon-announcements-and-news' |
'icon-camera-captures' |
'icon-firmware-upgrade' |
'icon-general-discussion' |
'icon-news' |
'icon-playsay-program' |
'icon-poe-cameras1' |
'icon-poe-camera-systems' |
'icon-product-release' |
'icon-reolink-client' |
'icon-reolink-mobile-app' |
'icon-security-cameras' |
'icon-security-systems' |
'icon-software' |
'icon-software-upgrade' |
'icon-suggestion-box' |
'icon-tips-and-tricks' |
'icon-top-reolinkcaptures-awards' |
'icon-wifi-cameras' |
'icon-wifi-camera-system' |
'icon-wire-free-cameras' |
'icon-color-night-vision' |
'icon-icon_2-Powering-Options' |
'icon-icon_3x-zoom' |
'icon-icon_4k-cycle' |
'icon-icon_4x-zoom' |
'icon-icon_8-channel2' |
'icon-icon_16-channel2' |
'icon-icon_24-7-recording' |
'icon-icon_123-TB' |
'icon-icon_1080p-82' |
'icon-icon_1440p-81' |
'icon-icon_audio' |
'icon-icon_battery-power' |
'icon-icon_ik10-vandal-proof-90' |
'icon-icon_motion-sensor1' |
'icon-icon_night-vision-89' |
'icon-icon_plug-and-play2' |
'icon-icon_poe-79' |
'icon-icon_pt' |
'icon-icon_sd-card' |
'icon-icon_Starlight-Night-Vision' |
'icon-icon_two-way-audio-84' |
'icon-icon_waterproof-80' |
'icon-icon_wifi-100' |
'icon-icon-detection-0723' |
'icon-product-banner-5x_zoom' |
'icon-product-banner-auto_tracking' |
'icon-product-banner-PTZ' |
'icon-product-banner-wide_viewing_angle' |
'icon-siren' |
'icon-spotlight-2' |
'icon-alerts-2' |
'icon-antennas2' |
'icon-Color-Night-Vision-2' |
'icon-ftp-30' |
'icon-HDD-Storage' |
'icon-HDD-Storage-2' |
'icon-icon_app-facet' |
'icon-icon_cloud1' |
'icon-icon_customized-voice-recordable-alerts-facet' |
'icon-icon_email-facet' |
'icon-icon_Rechargeable-facet' |
'icon-icon_siren-facet' |
'icon-icon_Starlight-facet' |
'icon-icon_talk-2' |
'icon-icon_voice' |
'icon-led' |
'icon-motion-detection-2' |
'icon-night-2' |
'icon-nvr-30' |
'icon-person-vehicle-detection-2' |
'icon-plug-play-2' |
'icon-product-fill-5x_zoom' |
'icon-product-fill-auto_tracking' |
'icon-product-fill-manual_pantilt' |
'icon-product-fill-motion_zone' |
'icon-product-fill-twin_Lenses' |
'icon-reliable-connection' |
'icon-sd-card-30' |
'icon-spotlight' |
'icon-subscription-2' |
'icon-viewing-angle' |
'icon-waterproof-2' |
'icon-wifi4' |
'icon-wire-free' |
'icon-X-Optical-Zoom' |
'icon-X-Optical-Zoom-line' |
'icon-TB' |
'icon-mp-line' |
'icon-TB1' |
'icon-1080p' |
'icon-p1' |
'icon-icon_3X-Optical-Zoom-line' |
'icon-icon_4-channel-line' |
'icon-icon_4G-3G-Mobile-Network' |
'icon-icon_4k' |
'icon-icon_4k1' |
'icon-icon_4X-Optical-Zoom-line' |
'icon-icon_5MP-4MP-line' |
'icon-icon_8-channel-line' |
'icon-icon_16-channel-line' |
'icon-icon_24-7-Recording-line' |
'icon-icon_120-Wide-Viewing-Angle' |
'icon-icon_130-Wide-Viewing-Angle' |
'icon-icon_180-Days' |
'icon-icon_1080p-hd2' |
'icon-icon_Day-and-Night-2' |
'icon-icon_detection-no-circle' |
'icon-icon_DIY-line' |
'icon-icon_Expand-System' |
'icon-icon_HDD-Storage-Built-in-line' |
'icon-icon_IK10-Vandal-Proof-line' |
'icon-icon_IK10-Vandal-Proof-line1' |
'icon-icon_Innovative-Installation-Design' |
'icon-icon_Innovative-Installation-Design1' |
'icon-icon_Intelligent-Alerts' |
'icon-icon_Local-Cloud-Storage-line' |
'icon-icon_Low-Battery-Notifications' |
'icon-icon_Mobile-Viewing-2' |
'icon-icon_Motion-Detection-Record' |
'icon-icon_Move-Anywhere' |
'icon-icon_Night-Vision-line' |
'icon-icon_Other-Smart-Features' |
'icon-icon_Plug-and-Play-line2' |
'icon-icon_Plug-and-Play-line21' |
'icon-icon_poe-cameras-line' |
'icon-icon_POE-line-2' |
'icon-icon_PoE-Systems-line' |
'icon-icon_Powering-Options-line' |
'icon-icon_product-PIR-Motion-Sensor' |
'icon-icon_product-Wire-Free' |
'icon-icon_PT-line' |
'icon-icon_PTZ-line' |
'icon-icon_PTZ-line1' |
'icon-icon_Rapid-Wake-Up' |
'icon-icon_Remote-Access' |
'icon-icon_See-Listen-and-Talk-line' |
'icon-icon_Share-Access' |
'icon-icon_simple-poe-or-dual-band-wifi1' |
'icon-icon_siren-line' |
'icon-icon_Starlight-Night-Vision-line' |
'icon-icon_Two-Way-Audio' |
'icon-icon_Waterproof-Design' |
'icon-icon_Wide-Viewing-Angle' |
'icon-icon_WiFi-Cameras-line' |
'icon-icon_WiFi-Cameras-Systems-line' |
'icon-icon_wifi-line' |
'icon-icon_WiFi-or-4G-Connection-line' |
'icon-icon_With-Audio-line' |
'icon-icon_Work-with-without-Internet-line' |
'icon-icon_Zoom_line' |
'icon-icon2_Customized-Voice-Recordable-Alerts' |
'icon-Motion-Zone-2' |
'icon-Plug-In-Power' |
'icon-pre-record' |
'icon-privacy-masking' |
'icon-product-outline-5mp' |
'icon-product-outline-5x_zoom' |
'icon-product-outline-auto_tracking' |
'icon-product-outline-duo' |
'icon-product-outline-go_pt' |
'icon-product-outline-hands_free_control' |
'icon-product-outline-local_storage' |
'icon-product-outline-nvr' |
'icon-product-outline-playback' |
'icon-product-outline-twin_Lenses' |
'icon-recording' |
'icon-sd-card-cloud' |
'icon-spotlight-line' |
'icon-wire-free-line' |
'icon-coupon2' |
'icon-icon_shipping' |
'icon-icon-coupon-0902' |
'icon-icon-Estimated-time-of-arrival' |
'icon-stock' |
'icon-alert-line' |
'icon-icon_16-sd-card' |
'icon-icon_app' |
'icon-icon_email' |
'icon-icon_ftp' |
'icon-motion-alerts' |
'icon-motion-zone' |
'icon-playback' |
'icon-schedule' |
'icon-simultaneous-live' |
'icon-battery-cam' |
'icon-icon_Accessories' |
'icon-icon_WiFi-Cameras-Systems-line1' |
'icon-indoor-cam' |
'icon-indoor-cam-discarded' |
'icon-indoor-cam-discarded1' |
'icon-kit' |
'icon-nvr' |
'icon-poe-cam' |
'icon-store-dual_lenses_cameras' |
'icon-wifi-cam' |
'icon-wifi-free-cam' |
'icon-wifi-poe-cam' |
'icon-bin' |
'icon-bin-line' |
'icon-firmware' |
'icon-hole-template' |
'icon-icon_ask-community' |
'icon-icon_cloud' |
'icon-icon_cloud-vedio' |
'icon-icon_contact-support' |
'icon-icon_screenshot' |
'icon-icon_stra' |
'icon-icon2-125' |
'icon-icon2-Accessories-checked' |
'icon-icon2-Clean--evaluate-products' |
'icon-icon2-Functional-test--firmware-upgrade' |
'icon-icon2-Product-returned' |
'icon-icon2-Repackaged--labeled-as-refurbished' |
'icon-icon2-Sold-as-Refurbished' |
'icon-icon-User-Manual-107' |
'icon-lab' |
'icon-qsg' |
'icon-pinterst-1' |
'icon-pinterst-2' |
'icon-Aliexpress' |
'icon-amazon' |
'icon-icon_amazon' |
'icon-icon_apple-store' |
'icon-icon_edge' |
'icon-icon_facebook' |
'icon-icon_facebook-2' |
'icon-icon_facebook-3' |
'icon-icon_facebook-4' |
'icon-icon_facebook-l' |
'icon-icon_firefox' |
'icon-icon_gmail-3' |
'icon-icon_google' |
'icon-icon_google-play' |
'icon-icon_ie' |
'icon-icon_ins' |
'icon-icon_ins-4' |
'icon-icon_mac-os' |
'icon-icon_safari' |
'icon-icon_twitter' |
'icon-icon_twitter-2' |
'icon-icon_twitter-3' |
'icon-icon_twitter-4' |
'icon-icon_twitter-l' |
'icon-icon_windows' |
'icon-icon_youtube-4' |
'icon-icon_youtube-logo' |
'icon-icon-reddit' |
'icon-Rating-3' |
'icon-Rating-2' |
'icon-Rating-1' |
'icon-unfold' |
'icon-pack-up' |
'icon-cross' |
'icon-day-line' |
'icon-hd' |
'icon-icon_3x' |
'icon-icon_5mp' |
'icon-icon_account' |
'icon-icon_back' |
'icon-icon_compare' |
'icon-icon_information' |
'icon-icon_night' |
'icon-icon_play-video' |
'icon-icon_support' |
'icon-icon_top' |
'icon-icon_youtube' |
'icon-icon-replay' |
'icon-listen-talk-line' |
'icon-night-line' |
'icon-pan-tilt-line' |
'icon-wifi3' |
'icon-icon_download' |
'icon-icon_cart-color' |
'icon-icon_reolink' |
'icon-icon_cart-2' |
'icon-icon_person-2' |
'icon-icon_search-2' |
'icon-icon_star-line' |
'icon-blog-cons' |
'icon-blog-pros' |
'icon-blog-note' |
'icon-blog-warning' |
'icon-check' |
'icon-attach-file' |
'icon-close' |
'icon-coupon' |
'icon-cross2' |
'icon-eye' |
'icon-hot' |
'icon-icon_arrow-down' |
'icon-icon_arrow-left' |
'icon-icon_arrow-right' |
'icon-icon_arrow-up' |
'icon-icon_back1' |
'icon-icon_caidan' |
'icon-icon_cart-99' |
'icon-icon_cart-992' |
'icon-icon_clock' |
'icon-icon_cross2' |
'icon-icon_edit' |
'icon-icon_full-screen' |
'icon-icon_have' |
'icon-icon_down-2' |
'icon-icon_right-2' |
'icon-icon_left-2' |
'icon-icon_play' |
'icon-icon_play-2' |
'icon-icon_plus' |
'icon-icon_question' |
'icon-icon_question1' |
'icon-icon_question2' |
'icon-icon_repeat' |
'icon-icon_Suppor' |
'icon-icon_vote' |
'icon-icon2_homepage' |
'icon-icon2_security' |
'icon-icon-arrow_down' |
'icon-icon-arrow_left' |
'icon-icon-arrow_right' |
'icon-icon-arrow_up' |
'icon-icon-check' |
'icon-icon-date' |
'icon-icon-download-2' |
'icon-icon-error' |
'icon-icon-error-2' |
'icon-icon-error-3' |
'icon-icon-error-4' |
'icon-icon-hint-count_down' |
'icon-icon-hint-error' |
'icon-icon-hint-success' |
'icon-icon-hint-warning' |
'icon-icon-hint-warning1' |
'icon-icon-loading-1' |
'icon-icon-loading-2' |
'icon-icon-navigation-back' |
'icon-icon-replay-2' |
'icon-icon-search-2' |
'icon-icon-share-2' |
'icon-icon-slide' |
'icon-icon-talk' |
'icon-right' |
'icon-question' |
'icon-MP' |
'icon-alert' |
'icon-day' |
'icon-listen' |
'icon-night' |
'icon-pan-tilt' |
'icon-phone' |
'icon-poe' |
'icon-poe-cameras' |
'icon-refund' |
'icon-sd-card' |
'icon-talk' |
'icon-waterproof' |
'icon-wifi';
